name: Release packages
permissions:
    actions: write
    contents: write
    packages: write
    checks: read
    pull-requests: write
    deployments: write

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}
on:
    push:
        branches:
            - main
jobs:
    pre_job:
        runs-on: ubuntu-latest
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@v5
              with:
                  # All of these options are optional, so you can remove them if you are happy with the defaults
                  concurrent_skipping: 'outdated_runs'
                  # paths_ignore: '["**/README.md", ".github/**"]'
                  cancel_others: 'true'

    release-packages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
                  ref: ${{ needs.check-app.outputs.branch }}

            - name: Prepare Environment
              uses: ./.github/actions/setup-env
              timeout-minutes: 10
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    @o2s:registry=https://registry.npmjs.org
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: npm run release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
